# Generated by Django 5.2.15 on 2026-06-08 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('section', models.CharField(max_length=20)),
                ('scope', models.CharField(default='PAR', max_length=20)),
                ('evidence_type', models.CharField(choices=[('out_time', 'Out-time / shelf-life records'), ('cure', 'Cure-cycle records'), ('documentation', 'Documentation (manual attestation)')], max_length=20)),
            ],
            options={
                'ordering': ['criterion_id'],
            },
        ),
        migrations.CreateModel(
            name='CriterionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_na', models.BooleanField(default=False)),
                ('na_explanation', models.TextField(blank=True)),
                ('procedure_reference', models.CharField(blank=True, max_length=200)),
                ('attested', models.BooleanField(default=False)),
                ('signed_by', models.CharField(blank=True, max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('criterion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='compliance.criterion')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='compliance.criterion')),
            ],
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('disposition', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncrs', to='compliance.criterion')),
            ],
            options={
                'verbose_name': 'NCR',
                'verbose_name_plural': 'NCRs',
                'ordering': ['-opened_at'],
            },
        ),
    ]
