# Generated by Django 5.2.15 on 2026-06-07 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('prepreg', 'Prepreg'), ('adhesive', 'Adhesive'), ('resin', 'Resin')], max_length=20)),
                ('default_out_time_limit', models.DurationField()),
                ('pot_life', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('manufactured_at', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('out_time_limit_override', models.DurationField(blank=True, null=True)),
                ('mixed_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='ColdStorageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('removed', 'Removed'), ('returned', 'Returned')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_events', to='materials.materiallot')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
