# Generated by Django 5.2.15 on 2026-06-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
