# Generated by Django 5.2.15 on 2026-06-08 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cure', '0001_initial'),
        ('materials', '0002_materiallot_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('lots', models.ManyToManyField(related_name='kits', to='materials.materiallot')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('cure_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='cure.curerun')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='trace.kit')),
            ],
        ),
    ]
