# Generated by Django 5.2.15 on 2026-06-07 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CureSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('soak_temp_min', models.FloatField()),
                ('soak_temp_max', models.FloatField()),
                ('soak_min_duration', models.DurationField()),
                ('ramp_rate_min', models.FloatField()),
                ('ramp_rate_max', models.FloatField()),
                ('pressure_min', models.FloatField()),
                ('pressure_max', models.FloatField()),
                ('vacuum_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CureRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('equipment_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('part_serials', models.JSONField(blank=True, default=list)),
                ('thermocouple_present', models.BooleanField(default=False)),
                ('process_panel_present', models.BooleanField(default=False)),
                ('profile', models.JSONField(blank=True, default=list)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='cure.curespec')),
            ],
        ),
    ]
